#数据库根路径
dbBaseDir: /home/user/001/workspaces/eclipse/mht2html2txt
#未找到处理器便抛异常
mvc: throw-exception-if-no-handler-found:true
server:
   port: 8080
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat
      uri-encoding: UTF-8
mybatis:
   mapperLocations: classpath:/mapper/*.xml
   typeAliasesPackage: com.mht2html2txt.allstar.bean
   mapperScanPackage: com.mht2html2txt.allstar.mapper
   configLocation: classpath:/MybatisConfig.xml
   configuration:
      map-underscore-to-camel-case: true #开启驼峰命名
spring:
   mvc:
      view:
         prefix: /templates/Htmls/
         suffix: .html
      static-path-pattern: /static/**
   resources:
      static-locations: classpath:/
      chain:
         strategy:
            content:
               enabled: true
               paths: /**
   thymeleaf:
      prefix: classpath:/templates/Htmls/
# DATASOURCE
   datasource:
      name: mht2html2txt
      url: jdbc:derby:${dbBaseDir}/mht2html2txt;create=true
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
      initialSize: 5
      minIdle: 5
      maxActive: 20
# 配置获取连接等待超时的时间
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
# 监控统计用的filter:stat;日志用的filter:log4j2;防御sql注入的filter:wall,用于防火墙
      filters: stat,log4j2
      validationQuery: select 1 from sysibm.sysdummy1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxOpenPreparedStatements: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# 设置合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: false
      druidLoginName: china # 登录druid的账号
      druidPassword: china # 登录druid的密码
      username: root
      password: root
   redis:
      timeout: 3000
# Redis服务器地址
      host: localhost
# Redis服务器连接端口
      port: 6379
# Redis服务器连接密码（默认为空）
      password: null
# 连接池最大连接数（使用负值表示没有限制）
      pool:
         max-active: 50
# 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: 30000
# 连接池中的最大空闲连接
         max-idle: 25
# 连接池中的最小空闲连接
         min-idle: 0
springfox.documentation.swagger.v2.path: /api-docs
logging:
   config: classpath:log4j2.xml